### ISSUE TITLE
ng generate preset --jest

### ISSUE THREAD

**Issue by GregOnNet** [kentan-official/kentan#3]
Kentan should make testing easier.

Instead of setting up jest manually for Angular projects.
Kentan can provide a schematic for that.

```bash
# Command
ng generate @kentan-official/schematics: jest-preset --suffix jest
```

## Planned Options
- `suffix` could be added to allow users to run jasmine and jest in parallel. (jest default: `/__tests__/.*|(\\.|/)(test|spec))\\.jsx?`)
  - We may change jest's default for Angular Projects
  - https://jestjs.io/docs/en/configuration.html#testmatch-array-string
- `remove-karma` (default: false)

## Tasks

- [ ] Install jest, jest angular preset
- [ ] Add jest-preset configuraiton to cli project
- [ ] Add jest scripts to package.json
- [ ] Eventually remove exisitng karma setup

**Comment by GregOnNet** [comment]
There is a package providing the described feature: https://www.npmjs.com/package/@briebug/jest

But for now, I do not want to drop this feature since the current implementation of **briebug** removes the Karma configuration: https://github.com/briebug/jest-schematic/blob/master/src/jest/index.ts#L51

That behaviour does not serve existing projects.

Nevertheless, this schematic gives a good idea which tasks we need to implement.
